export const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_TOTAL: "SET_TOTAL",
  ADD_PRODUCTS_INTO_CART: "ADD_PRODUCTS_INTO_CART",
  SET_SINGLE_PRODUCTS: "SET_SINGLE_PRODUCTS",
  SET_MODEL: "SET_MODEL",
  CLOSE_MODEL: "CLOSE_MODEL",
  CLEAR_CART: "CLEAR_CART",
  REMOVE_A_ITEM_CART: "REMOVE_A_ITEM_CART",
  UPDATED_CART: "UPDATED_CART",
};
