export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    ADD_PRODUCTS:"ADD_PRODUCTS",
    REMOVE_PRODUCTS:"REMOVE_PRODUCTS",
    UPDATE_PRODUCTS:"UPDATE_PRODUCTS"
}